export const FIELD_TYPE = {
	TAGS: 'tags',
	BOOLEAN_TAGS: 'booleanTags',
	NUMBER_TAGS: 'numberTags',
	MULTI_IMAGE: 'multiImage',
	SINGLE_IMAGE: 'singleImage',
	SINGLE_FILE: 'singleFile',
	MULTIPLE: 'multiple',
	MULTI_FILE: 'multiFile',
	PRIVATE_SINGLE_FILE: 'privateSingleFile',
	MULTI_PRIVATE_FILE: 'multiPrivateFile',
	TEXT: 'text',
	LONG_TEXT: 'longText',
	RICH_TEXT: 'richText',
	NUMBER: 'number',
	CHECKBOX: 'checkbox',
	EMAIL_ADDRESS: 'emailAddress',
	WEBSITE_URL: 'websiteUrl',
	COLOR: 'color',
	VIDEO_URL: 'videoUrl',
	DATE: 'date',
	DATE_TIME: 'datetime',
	PASSWORD: 'password',
	MULTISELECT_LIST: 'multiselectList',
	DROPDOWN_LIST: 'dropdownList',
	DYNAMIC_FIELD_ARRAY: 'dynamicFieldArray',
};
